### ISSUE TITLE
Missing service worker support

### ISSUE THREAD

**Issue by marksmall** [MasterKale/django-cra-helper#1]
It appears there is no support provided for **Service Workers**, am I correct? If so, this necessary to properly support **create-react-app**.

I would expect it to work similarly to the **Manifest** solution provided, I guess.

If I'm wrong about this, can you point me towards how to support **Service Workers** in my app.

**Comment by MasterKale** [comment]
My intention in creating this library was to allow for development of individual components using **create-react-app** that could then be used here and there in traditional Django views. The Django views would still be rendered server side, but **django-cra-helper** would help handle bundling all of the JS for inclusion in a master template.

I'm definitely not advocating for using **django-cra-helper** to serve an entire React app from a single Django view!

Would service workers make sense if your website isn't a SPA?

**Comment by marksmall** [comment]
Wow, thanks for the quick response.

Our app is a SPA served through a single Django view, not saying it is the best way, it's legacy code (that's my get-out-of-jail card...).

Our mistake then in considering this as a means to link a React app to a single Django view.

Thanks for your response.

**Comment by MasterKale** [comment]
Given that service worker registration happens entirely on the client side, I think you could still get service worker support in your situation by making sure the `registerServiceWorker()` call and related JS logic gets bundled into the CRA codebase. I don't foresee **django-cra-helper** preventing you from accomplishing that at all!
