### ISSUE TITLE
Live reloading requests for hot-update paths fail

### ISSUE THREAD

**Issue by kamal** [MasterKale/django-cra-helper#12]
When live reloading is happening, the bundle will request HMR manifest, JS and sourcemap files. I had to add the following paths to `proxy_urls`

```python
    proxy_urls = [
        re_path(r'^__webpack_dev_server__/(?P<path>.*)$', proxy_cra_requests),
        re_path(r'^(?P<path>.+\.hot-update\.(js|json|js\.map))$', proxy_cra_requests),
    ]
```

**Comment by MasterKale** [comment]
Thank you for pointing this out, it looks like it's just the second path I need to add to the docs.

@kamal Can you confirm your project's version of `react-scripts`?

**Comment by kamal** [comment]
@MasterKale it's 3.4.1

**Comment by MasterKale** [comment]
I've added that second proxy URL to the README:

https://github.com/MasterKale/django-cra-helper#2-urlspy

Thank you for your contribution, this is a much smoother hot-reload setup than what I'd been able to achieve :)
