### ISSUE TITLE
How to add routes from react-router-dom?

### ISSUE THREAD

**Issue by CR1AT0RS** [MasterKale/django-cra-helper#15]
@MasterKale 
This project is awesome. Thanks for putting this together. I am using React-router:
```

const App = () => (
  <BrowserRouter>
    <Provider store={store}>
      <Fragment>
        <div className="App">
          <Switch>
            <Route exact path={"/login"} component={Login} />
            <Route exact path={"/home"} component={MainPage} />
            <Route path={"/"} component={Login} />
          </Switch>
        </div>
      </Fragment>
    </Provider>
  </BrowserRouter>
);

export default App;
```

Any time I try to visit these paths the app defaults to DJANGO paths. How do I enable react routes with this integration?
<img width="642" alt="Screen Shot 2020-08-02 at 7 34 40 PM" src="https://user-images.githubusercontent.com/4299288/89140720-5073d300-d4f7-11ea-8aaa-bf18c980190c.png">

**Comment by MasterKale** [comment]
I'm going to close this out since you cracked the case with PR #16 ✌️
