### ISSUE TITLE
Webpack compile error in both Safar and Firefox latest version

### ISSUE THREAD

**Issue by CR1AT0RS** [MasterKale/django-cra-helper#17]
So my application works fine on chrome but on both safari and Chrome I get the following errors:

1. Safari  ReferenceError: Can't find variable: BigInt
<img width="518" alt="Screen Shot 2020-08-04 at 7 16 24 PM" src="https://user-images.githubusercontent.com/4299288/89364494-7203c480-d687-11ea-8804-115451c3a847.png">

2. Firefox: Uncaught ReferenceError: SharedArrayBuffer is not defined
<img width="661" alt="Screen Shot 2020-08-04 at 7 17 42 PM" src="https://user-images.githubusercontent.com/4299288/89364518-7d56f000-d687-11ea-8f09-63deec11af38.png">

I have enabled the javascript.options.shared_memory: True in about:config
<img width="792" alt="Screen Shot 2020-08-04 at 7 17 51 PM" src="https://user-images.githubusercontent.com/4299288/89364556-8fd12980-d687-11ea-8244-811ab338b921.png">

Not sure if we are loading the js files in wrong order maybe? 
@MasterKale

**Comment by MasterKale** [comment]
According to caniuse Safari doesn't support BigInt so you'll need to polyfill it: https://caniuse.com/#feat=bigint

As for `SharedArrayBuffer` in Firefox, are you on v79? They only just recently re-enabled support for that, and only under very specific circumstances: https://hacks.mozilla.org/2020/07/safely-reviving-shared-memory/

None of these are immediately related to this library, though, so unless you're able to identify `cra_helper` as the cause of this in a day or two then I'll end up closing this issue.

**Comment by CR1AT0RS** [comment]
Thanks! I think it was resolved after I removed the antd-landing js dependencies. Which uses some old stuff! Thank for your quick response :)
