### ISSUE TITLE
CRA over external interface dev build

### ISSUE THREAD

**Issue by CR1AT0RS** [MasterKale/django-cra-helper#20]
Hey,

I am trying to build the CRA over a dev instance. I am using an external interface. 

So for example my Django is bound to port 0.0.0.0:443 and my cra is bound to port 0.0.0.0 3000
But I am accessing the website with:  example.test.com externally. But the scripts for cra are not loading in dev from example.test.com:3000. As I am running in DEBUG instance. How can I make a non localhost setup work? 

Sorry this is a bit confusing but happy to provide more context and any questions you have.

**Comment by MasterKale** [comment]
Is **example.test.com** pointing to an external IP? Internal IP? It sounds like it might be a firewall issue if CRA is indeed listening on `0.0.0.0:3000`. Are you sure port 3000 is open and pointed at your machine?

I'm not sure how this is related to this library at all, as development assumes everything is hosted locally. If you're trying to access a site for testing on other devices, try creating an A-record subdomain to a local IP address (e.g. "192.168.x.x") and then turning off your dev machine's firewall for intranet connections. Devices on your same network will be able to access your site without exposing everything to the wider internet. That's how I do it, anyway...
