### ISSUE TITLE
Document that the `FileSystemFinder` needs to be in `STATICFILES_FINDERS`

### ISSUE THREAD

**Issue by ralokt** [MasterKale/django-cra-helper#21]
If the CRA liveserver is not running, django-cra-helper makes its assets findable to `collectstatic` by putting them into `STATICFILES_DIRS`:

https://github.com/MasterKale/django-cra-helper/blob/e65ff34f6397e5158ea74ef43c3c8401d58955f3/cra_helper/asset_manifest.py#L57

`STATICFILES_DIRS` is used by `"django.contrib.staticfiles.finders.FileSystemFinder"`, so this only works if this finder is in `STATICFILES_FINDERS`. While the default `settings.py` generated for new Django projects includes it, it's also not unheard of to remove it - for example, when you turn your project into an app itself.

It would therefore be great if there were a short note in the README specifying that this is required (and not just a django default).

https://github.com/MasterKale/django-cra-helper/blob/e65ff34f6397e5158ea74ef43c3c8401d58955f3/README.md#L73

Would have saved me a dive into the source code of the project just now.

**Comment by MasterKale** [comment]
Thank you for explaining why `STATICFILES_DIRS` might not be present in **settings.py**. I've updated the README with additional emphasis on the importance of `FileSystemFinder`:

> Additionally, the following `STATICFILES_FINDERS` list must be added to `settings.py`:
> 
> ```python
> STATICFILES_FINDERS = [
>     # Required for CRAManifestFinder below to work
>     'django.contrib.staticfiles.finders.FileSystemFinder',
>     # A finder to pull in asset-manifest.json
>     'cra_helper.finders.CRAManifestFinder',
> ]
> ```

**Comment by ralokt** [comment]
Better late than never - thanks, glad to see that this made it in!
