### ISSUE TITLE
Liveserver integration does not work with react-scripts@4.x

### ISSUE THREAD

**Issue by zrev2220** [MasterKale/django-cra-helper#26]
Using react-scripts@4.0.2, the instructions for getting Django to work with React's liveserver don't seem to work. The filenames in the `bundle_js` template variable aren't the same as the script filenames the liveserver loads.

Here's a comparison:

| | React Liveserver | Django |
|-|-|-|
| Loaded scripts | ![image](https://user-images.githubusercontent.com/22283396/108640351-20762800-7467-11eb-9409-2fca1c064148.png) | ![image](https://user-images.githubusercontent.com/22283396/108640361-3257cb00-7467-11eb-82aa-883d0a418649.png)
| Result | ![image](https://user-images.githubusercontent.com/22283396/108640414-8367bf00-7467-11eb-9261-1205d6c0ef53.png) | ![image](https://user-images.githubusercontent.com/22283396/108640428-8e225400-7467-11eb-9e0b-106f1078a8f1.png) <sub>(blank screen)</sub>

Specifically, `django-cra-helper` is loading `0.chunk.js`, while the React liveserver is loading `vendors~main.chunk.js` instead.

Here's my template file that Django is loading:

```html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <title>django-cra-helper liveserver bug</title>

    {% if entrypoints %}
      {% for file in entrypoints.css %}
        <link href="{% static file %}" rel="stylesheet" />
      {% endfor %}
    {% elif main_css %}
      <link href="{% static main_css %}" rel="stylesheet" />
    {% endif %}
  </head>
  <body>
    <div id="root">{# React frontend gets rendered here #}</div>
    {% if bundle_js %}
      {% for file in bundle_js %}
        <script type="text/javascript" src="{{ file }}"></script>
      {% endfor %}
      {# django-cra-helper liveserver integration does not work without this script #}
      <!-- <script
        type="text/javascript"
        src="http://localhost:3000/static/js/vendors~main.chunk.js"
      ></script> -->
    {% elif entrypoints %}
      {% for file in entrypoints.js %}
        <script type="text/javascript" src="{% static file %}"></script>
      {% endfor %}
    {% endif %}
  </body>
</html>
```

If I manually load the `vendors~main.chunk.js` script (commented out in that snippet 👆), then everything works as I'd expect; the app loads correctly, and changes to files are detected properly.

[Here's a reproduction repo](https://github.com/zrev2220/django-cra-helper-liveserver-bug) if it helps.

I think the solution involves the lines of code below. Fixing the issue may simply involve adding to/modifying what `django-cra-helper` puts in the `bundle_js` array.

https://github.com/MasterKale/django-cra-helper/blob/e65ff34f6397e5158ea74ef43c3c8401d58955f3/cra_helper/asset_manifest.py#L39-L46

**Comment by MasterKale** [comment]
@zrev2220 Thank you for bringing this issue up. This issue should be resolved in PR #27. The fix is availbe in the newly-published **django-cra-helper==2.0.0**.

(This release shouldn't require any changes to your code related to this issue - the major version release is because I broke the package's API by removing its `json` template tag for built-in Django functionality.)
