### ISSUE TITLE
Code splitting support for live server

### ISSUE THREAD

**Issue by squidsoup** [MasterKale/django-cra-helper#3]
CRA v2 uses code splitting, producing 3 assets by default when the live server is run:

**bundle.js**
Bootstrapping/liveserver code presumably.

**main.chunk.js**
Main application code.

**0.chunk.js**
Vendor code.

Currently `django-cra-helper` only supports returning the bundle path in `generate_manifest`.

[More details](https://github.com/facebook/create-react-app/issues/5754#issuecomment-437262168)

Unfortunately this is complicated by [a lack of a coherent asset manifest in CRA2](https://github.com/facebook/create-react-app/issues/5513).

**Comment by MasterKale** [comment]
Thanks for raising this. Right off the top of my head, the "easy" solution would be to add in a couple of more hard-coded paths to `generate_manifest()` to use when the liveserver is detected. I wonder if there's a way to do it in a way that'll future-proof this library to accommodate potential future changes to CRA...

I'll have to mull over this for a couple of days and see if anything doesn't come to mind.

**Comment by MasterKale** [comment]
I've released **django-cra-helper v1.2.0** that includes support for the various forms that **asset-manifest.json** has taken over the last few releases of Create-React-App. Give it a try and let me know what you think! 🎉
